title: regimeketo.com
author: Mahassine
email: regimeketo@gmail.com
facebook_username: regimeketo
instagram_username: regimeketo
twitter_username: regimeketo
youtube_username: Régime Keto
youtube_channel: channel/UCVtDhoTk3c4ojEhlrIqilNQ
pinterest_username: regimeketo
github_username: regimeketo
rss: News Feed

description: >-
  Premier site francophone entièrement dédié à la perte de poids
  durable par la diète cétogène
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  recipes:
    output: true
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
